### PR TITLE
Add libgmock-dev to installation instructions

### PR DESCRIPTION
**Pull request by CaledoniaProject**

### CODE REVIEW

**Comment by kesheldr** [comment]
Hello.

Thanks for your input. Can I ask which systems is this required for? Maybe it could be broken out into a separate line specifically for those that need it?

Thanks

**Comment by CaledoniaProject** [comment]
@kesheldr Ubuntu 20.04

**Comment by hillu** [comment]
> @kesheldr Ubuntu 20.04

I can confirm this.

**Comment by kesheldr** [comment]
So I'm confused. I just span up a new Ubuntu 20.04 on Azure, kernel v5.11, apt all up to date, and followed the instructions in the README verbatim and it built without needing libgmock-dev.
I'm wondering if libgmock-dev would replace the manual building of googletest?
This package doesn't exist on Ubuntu 18.04, so I'd need specific/different instructions for each if we're to include it.
Please can you check again and let me know?
Many thanks.

**Comment by CaledoniaProject** [comment]
@kesheldr My Ubuntu 20.04 is installed from ISO image, not an azure VM

**Comment by kesheldr** [comment]
@CaledoniaProject I appreciate there will be a difference, but Azure images don't come with libgmock-dev, and my Ubuntu 20.04 doesn't have it installed. Did you build googletest as described in the instructions, or is the libgmock-dev an alternative for building it?
Thanks.

**Comment by CaledoniaProject** [comment]
I didn't do anything, just following the instructions in README

**Comment by CaledoniaProject** [comment]
I've decided not to waste more time on this issue, closing it.

**Pull request closed without merging**
